# Generated by Django 4.1.7 on 2023-02-22 15:43

from django.db import migrations
from django.core.management import call_command


def start_func(state, schema_editor):
    call_command('loaddata', 'user_fixture.json')


def reverse_start_func(state, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(start_func, reverse_start_func)
    ]
